<?php
$data=yaml_parse_file('donnée.yaml');

?>


<!DOCTYPE html>
<html lang="fr">
<link rel="stylesheet" href="principal.css">
<script src="https://kit.fontawesome.com/7ca312f99b.js" crossorigin="anonymous"></script>
<body>
	<div id="APropos">
		<h1 id='titre'>Mes expériences :</h1>
		<div id='presentation'>
			<img id='pdp' src='pdp.jpg'> 
			<p id='texte'> jbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjiojbktqhdsivjZ	MBETKQDSVOPIHAT3BJZ GQDSVHOAEQGDSYUOIFEA ZTBEGHQDSVFIOPHEZGQDSFUIOP QGERHIQEUIPAOTZ4HQGREUIYJZHJRS GUIPgorijhtrsipejjsgdh ijejrsgjio</p>
			<p id='accroche'>Dans le royaume du digital, Houette crée sans défaite.</p>	
		</div> 
	</div>
	
</body>
</html>
